-- =====================================================================================
-- Web Push phase 1 (2026-09-26): remote push foundation.
--
-- 1. push_subscriptions: one row per browser (endpoint unique), RLS auth.uid() = user_id.
-- 2. push_subscribe(): idempotent upsert on endpoint for the signed-in account.
-- 3. Server secrets live in Supabase Vault, never in the repo nor in the browser:
--      push_vapid_public / push_vapid_private  -> generated BY the send-push Edge Function
--                                                 on its first run (the private key never
--                                                 leaves the server)
--      push_internal_secret                     -> generated here, shared secret between
--                                                 notify_users() and send-push
--    push_server_config() / push_store_vapid() are executable by service_role only.
-- 4. notify_users(): server-side entry point (pg_net -> send-push, internal secret).
--    Not executable by anon nor authenticated: only other server functions call it.
-- 5. users.notification_preferences: drift fix (field exists in the local model).
-- IDEMPOTENT: if not exists / create or replace / drop policy if exists.
-- =====================================================================================

create extension if not exists pg_net with schema extensions;

-- ---------------------------------------------------------------------------------
-- 1. Table
-- ---------------------------------------------------------------------------------
create table if not exists public.push_subscriptions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  cree_le timestamptz not null default now(),
  derniere_utilisation timestamptz,
  echecs_consecutifs int not null default 0
);
create unique index if not exists push_subscriptions_endpoint_uniq on public.push_subscriptions (endpoint);
create index if not exists push_subscriptions_user_idx on public.push_subscriptions (user_id);

alter table public.push_subscriptions enable row level security;
revoke all on public.push_subscriptions from anon;

drop policy if exists push_subscriptions_select_own on public.push_subscriptions;
create policy push_subscriptions_select_own on public.push_subscriptions
  for select to public using (auth.uid() = user_id);

drop policy if exists push_subscriptions_insert_own on public.push_subscriptions;
create policy push_subscriptions_insert_own on public.push_subscriptions
  for insert to public with check (auth.uid() = user_id);

drop policy if exists push_subscriptions_update_own on public.push_subscriptions;
create policy push_subscriptions_update_own on public.push_subscriptions
  for update to public using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists push_subscriptions_delete_own on public.push_subscriptions;
create policy push_subscriptions_delete_own on public.push_subscriptions
  for delete to public using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------------
-- 2. Subscribe (upsert on endpoint). SECURITY DEFINER so that a browser previously
--    used by another account is handed over to the account signed in now, instead of
--    failing on a row the caller cannot see. The caller is always auth.uid().
-- ---------------------------------------------------------------------------------
create or replace function public.push_subscribe(
  p_endpoint text, p_p256dh text, p_auth text, p_user_agent text default null
) returns uuid
language plpgsql security definer set search_path = public as $$
declare
  v_uid uuid := auth.uid();
  v_id uuid;
begin
  if v_uid is null then
    raise exception 'not authenticated' using errcode = '42501';
  end if;
  if coalesce(p_endpoint, '') !~ '^https://' or coalesce(p_p256dh, '') = '' or coalesce(p_auth, '') = '' then
    raise exception 'invalid subscription' using errcode = '22023';
  end if;

  insert into public.push_subscriptions (user_id, endpoint, p256dh, auth, user_agent)
  values (v_uid, p_endpoint, p_p256dh, p_auth, left(p_user_agent, 300))
  on conflict (endpoint) do update
    set user_id = excluded.user_id,
        p256dh = excluded.p256dh,
        auth = excluded.auth,
        user_agent = excluded.user_agent,
        echecs_consecutifs = 0
  returning id into v_id;
  return v_id;
end;
$$;
revoke execute on function public.push_subscribe(text, text, text, text) from public, anon;
grant execute on function public.push_subscribe(text, text, text, text) to authenticated;

-- ---------------------------------------------------------------------------------
-- 3. Server secrets (Vault)
-- ---------------------------------------------------------------------------------
do $$
begin
  if not exists (select 1 from vault.secrets where name = 'push_internal_secret') then
    perform vault.create_secret(encode(extensions.gen_random_bytes(32), 'hex'), 'push_internal_secret',
                                'Shared secret notify_users -> send-push');
  end if;
end $$;

create or replace function public.push_server_config()
returns table (vapid_public text, vapid_private text, internal_secret text)
language sql stable security definer set search_path = public, vault as $$
  select
    (select decrypted_secret from vault.decrypted_secrets where name = 'push_vapid_public'),
    (select decrypted_secret from vault.decrypted_secrets where name = 'push_vapid_private'),
    (select decrypted_secret from vault.decrypted_secrets where name = 'push_internal_secret');
$$;
revoke execute on function public.push_server_config() from public, anon, authenticated;
grant execute on function public.push_server_config() to service_role;

-- Stores the VAPID pair ONCE (never overwrites: existing subscriptions are bound to it).
create or replace function public.push_store_vapid(p_public text, p_private text)
returns text
language plpgsql security definer set search_path = public, vault as $$
begin
  perform pg_advisory_xact_lock(hashtext('push_store_vapid'));
  if not exists (select 1 from vault.secrets where name = 'push_vapid_public') then
    perform vault.create_secret(p_private, 'push_vapid_private', 'Web Push VAPID private key');
    perform vault.create_secret(p_public, 'push_vapid_public', 'Web Push VAPID public key');
  end if;
  return (select decrypted_secret from vault.decrypted_secrets where name = 'push_vapid_public');
end;
$$;
revoke execute on function public.push_store_vapid(text, text) from public, anon, authenticated;
grant execute on function public.push_store_vapid(text, text) to service_role;

-- ---------------------------------------------------------------------------------
-- 4. notify_users: app events (e.g. NAVY parcels) -> send-push, internal path.
--    Body must stay non-sensitive: short title + link to the screen.
-- ---------------------------------------------------------------------------------
create or replace function public.notify_users(
  p_user_ids uuid[], p_title text, p_body text, p_url text
) returns bigint
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_secret text;
  v_request_id bigint;
begin
  if coalesce(array_length(p_user_ids, 1), 0) = 0 then
    return null;
  end if;
  select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'push_internal_secret';
  if v_secret is null then
    raise exception 'push_internal_secret missing';
  end if;

  select net.http_post(
    url := 'https://ofzmwrzatcztoekrpvkj.supabase.co/functions/v1/send-push',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      -- public anon key: only satisfies the gateway JWT check; the real auth is x-push-internal
      'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mem13cnphdGN6dG9la3JwdmtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjAxMTUsImV4cCI6MjA3NDczNjExNX0.hYDpbvzwNZWmDgXPSGEgoKLR-m51TQZmaWw1whQ90Cw',
      'x-push-internal', v_secret
    ),
    body := jsonb_build_object(
      'user_ids', to_jsonb(p_user_ids),
      'titre', left(coalesce(p_title, ''), 120),
      'corps', left(coalesce(p_body, ''), 300),
      'url', coalesce(p_url, '/')
    ),
    timeout_milliseconds := 10000
  ) into v_request_id;
  return v_request_id;
end;
$$;
revoke execute on function public.notify_users(uuid[], text, text, text) from public, anon, authenticated;

-- ---------------------------------------------------------------------------------
-- 5. Drift: User.notificationPreferences exists in the local model, not in the table.
-- ---------------------------------------------------------------------------------
alter table public.users add column if not exists notification_preferences jsonb;
